# Generated by Django 3.2.25 on 2024-04-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_journaling_meditation_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='No Name Yet', help_text='Enter the full name of the person', max_length=100),
        ),
    ]
