# Generated by Django 3.2.25 on 2024-04-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_journaling_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaling',
            name='entry_text',
            field=models.TextField(blank=True),
        ),
    ]
